language: java
jdk:
  - oraclejdk8
install:

mvn sonar:
- mvn clean compile sonar  -Dsonar.organization=julienvieaud-github  -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=6797431fccca94052808f417abe431df31e85fab
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
